package Day14;

public class TestNgArchiteture {
	
	
	// TAGS/ANNOTATIONS
	
	//  @TEST - EXECUTION PLACE [3RD PLACE]
	
	//  @BEFORETEST - WILL EXECUTE BEFORE ALL YOUR TAGS [1ST PLACE]
	
	// @BEFORE METHOD - IT WILL EXECUTE BEFORE @TEST [2ND PLACE]
	
	// @AFTERMETHOD - IT WILL EXECUTE AFTER @TEST [4TH PLACE]
	
	// @AFTERTEST - IT IS THE LAST PART IN OUR EXECUTION [5TH PLACE]
	
}

